version: '2.1'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: goservice
      POSTGRES_PASSWORD: Go-SeRvIcE482
      POSTGRES_DB: goservice
      POSTGRES_PORT: 5432
    ports: 
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U goservice"]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    build:
        dockerfile: Dockerfile
        context: .
    ports:
      - 8088:8088
    depends_on:
      postgres:
        condition: service_healthy